### ISSUE TITLE
Blank page after login

### ISSUE THREAD

**Issue by CyberM0nster** [j3ssie/osmedeus#258]
After login on web ui 
![1](https://github.com/j3ssie/osmedeus/assets/15001515/a0212427-7973-4281-9f67-3ea8dcc01ddd)

the application shows a blank page
![image](https://github.com/j3ssie/osmedeus/assets/15001515/d9243061-2a1f-47d5-a90c-8c1eeb358c9d)

but, it's possible to use the application changing the URL
![image](https://github.com/j3ssie/osmedeus/assets/15001515/ee26fce8-c76b-4b4b-8df5-0fd3b19ed226)

**Comment by tienhuyvonguyen** [comment]
same issue

**Comment by j3ssie** [comment]
Hmm, I just pushed the latest change for the UI. I 

Can you guys try a fresh install by running `rm -rf ~/osmedeus-base ~/.osmedeus` and then run the install script again to have a clean installation?

Maybe try in the incognito to make sure the cache is clear as well

**Comment by lazyest** [comment]
In my particular case it returning  wrong auth for a sec and then redirecting to blank page. Checked in several different deployments.

**Comment by P4r4n01dB34r** [comment]
As of today this problem is not resolved on latest version v4.6.3
