### ISSUE TITLE
Error when running the tool on Kali Linux 2019.01

### ISSUE THREAD

**Issue by sumgro** [j3ssie/Osmedeus#6]
./osmedeus.py -m subdomain -t <target.com>                                                                         1 ↵

                       `@@`
                      @@@@@@
                    .@@`  `@@.
                    :@      @:
                    :@  :@  @:                       
                    :@  :@  @:                       
                    :@      @:                             
                    `@@.  .@@`
                      @@@@@@
                        @@
                     @  @@  @               
                    +@@ @@ @@+                    
                 @@:@#@,@@,@#@:@@           
                ;@+@@`#@@@@#`@@+@;
                @+ #@@@@@@@@@@# +@
               @@  @+`@@@@@@`+@  @@
               @.  @   ;@@;   @  .@
              #@  '@          @;  @#

                     
             Osmedeus v1.0 by @j3ssiejjj

                    ¯\_(ツ)_/¯
        
[*] Config file detected: core/config.conf
--~~~=:>[ Staarting Flask API ]>
[-] Something wrong to connect to {0}
Traceback (most recent call last):
  File "/root/PenTest/OSINT/Osmedeus/core/config.py", line 136, in parsing_config
    ip = socket.gethostbyname(strip_target)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./osmedeus.py", line 151, in <module>
    main()
  File "./osmedeus.py", line 147, in main
    parsing_argument(args)
  File "./osmedeus.py", line 50, in parsing_argument
    options = config.parsing_config(config_path, args)
  File "/root/PenTest/OSINT/Osmedeus/core/config.py", line 139, in parsing_config
    utils.print_bad("Something wrong to connect to {0}").format(target)
AttributeError: 'NoneType' object has no attribute 'format'
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "core/app.py", line 238, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 812, in run_simple
    reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 266, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 171, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)

**Comment by j3ssie** [comment]
My bad typo when connection error to the target.
It's should be fixed now.

**Comment by sumgro** [comment]
Hi,

Still getting the error when attempting to use the tool. 

-----
[*] Config file detected: core/config.conf
--~~~=:>[ Staarting Flask API ]>
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "core/app.py", line 238, in <module>
    app.run(debug=True)  # important to mention debug=True
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/serving.py", line 812, in run_simple
    reloader_type)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 266, in run_with_reloader
    reloader = reloader_loops[reloader_type](extra_files, interval)
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/_reloader.py", line 171, in __init__
    from watchdog.observers import Observer
ImportError: cannot import name 'Observer' from 'watchdog.observers' (unknown location)
[+] Make new workspace: /root/PenTest/OSINT/Osmedeus/workspaces/target.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2d9ff10978>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d9ff10978>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./osmedeus.py", line 151, in <module>
    main()
  File "./osmedeus.py", line 147, in main
    parsing_argument(args)
  File "./osmedeus.py", line 54, in parsing_argument
    utils.set_config(options)
  File "/root/PenTest/OSINT/Osmedeus/core/utils.py", line 135, in set_config
    r = requests.post(url, headers=headers, json=data)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d9ff10978>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by j3ssie** [comment]
Look like requests library is missing from your OS.
So you may wanna check this out [Install Guide](https://github.com/j3ssie/Osmedeus/wiki#installation-in-detail)

**Comment by sumgro** [comment]
I've verified both pip and python requests library is installed. Still reinstalled it, but still getting the same error.

This was working fine till sometime in Feb'19. Not sure of what had broken this... I've tried a fresh clone and install process, but in vain.

**Comment by sumgro** [comment]
Apparently, did a fresh VM and installed the tool. The tool worked without any issues...any suggestion on how to resolve this on the current setup shall be really great.

Thanks

**Comment by j3ssie** [comment]
yeah just DM @j3ssiejjj
